options(stringsAsFactors=FALSE)
suppressPackageStartupMessages({library(Matrix);library(data.table);library(edgeR);library(ggplot2);library(ragg)})
root <- "D:/PDAC_P1"; raw <- file.path(root,"data/03_spatial/GSE327056/raw"); out <- file.path(root,"analysis/09_spatial_validation"); plot_out <- "D:/PDAC_spatial_plot_tmp"; dir.create(plot_out,recursive=TRUE,showWarnings=FALSE)
cand <- fread(file.path(root,"analysis/07_candidate_screen/candidate_genes_stable_high_confidence_all.tsv"))[candidate_status=="screening_candidate" & major_lineage %in% c("endothelial","T_NK")]
programs <- lapply(split(cand,cand$major_lineage),function(x)list(up=x[direction=="tumor_up",gene_id],down=x[direction=="tumor_down",gene_id],all=x$gene_id))
samples <- data.table(tag=c("A1","B1","C1","D1"),gsm=c("GSM9647219","GSM9647220","GSM9647221","GSM9647222"),context=c("adjacent_tumor","tumor","tumor_stroma","normal_pancreas"))
expr <- list(); pos_list <- list(); meta_list <- list(); gene_union <- unique(unlist(lapply(programs,function(x)x$all)))
for(i in seq_len(nrow(samples))) {
  s <- samples[i]; pre <- paste0(s$gsm,"_",s$tag); mat <- readMM(gzfile(file.path(raw,paste0(pre,"_matrix.mtx.gz")))); feat <- fread(file.path(raw,paste0(pre,"_features.tsv.gz")),header=FALSE); bar <- fread(file.path(raw,paste0(pre,"_barcodes.tsv.gz")),header=FALSE); pos <- fread(file.path(raw,paste0(pre,"_tissue_positions.csv.gz")))
  rownames(mat) <- make.unique(if(ncol(feat)>=2) feat[[2]] else feat[[1]]); colnames(mat) <- bar[[1]]; pos <- pos[in_tissue==1 & barcode %in% colnames(mat)]; ids <- intersect(pos$barcode,colnames(mat)); pos <- pos[match(ids,pos$barcode)]; mat <- mat[,ids,drop=FALSE]
  lc <- cpm(DGEList(counts=mat),log=TRUE,prior.count=2); g <- intersect(gene_union,rownames(lc)); expr[[s$tag]] <- lc[g,,drop=FALSE]; pos_list[[s$tag]] <- pos; meta_list[[s$tag]] <- s; rm(mat,lc); gc(verbose=FALSE)
}
all_genes <- unique(unlist(lapply(expr,rownames))); all_expr <- do.call(cbind,lapply(expr,function(x){z<-matrix(NA_real_,nrow=length(all_genes),ncol=ncol(x),dimnames=list(all_genes,colnames(x)));z[rownames(x),]<-x;z})); mu <- rowMeans(all_expr,na.rm=TRUE); sig <- apply(all_expr,1,sd,na.rm=TRUE); sig[!is.finite(sig)|sig==0] <- 1
sum_rows <- list(); spot_rows <- list()
for(i in seq_len(nrow(samples))) {
  s <- samples[i]; z <- (expr[[s$tag]][all_genes,,drop=FALSE]-mu[all_genes])/sig[all_genes]; one <- data.table(dataset="GSE327056",tag=s$tag,gsm=s$gsm,context=s$context,barcode=colnames(z)); p <- pos_list[[s$tag]][match(one$barcode,pos_list[[s$tag]]$barcode)]; one[,`:=`(array_row=p$array_row,array_col=p$array_col,pxl_row_in_fullres=p$pxl_row_in_fullres,pxl_col_in_fullres=p$pxl_col_in_fullres)]
  for(program in names(programs)) {g <- programs[[program]]; up <- intersect(g$up,rownames(z)); down <- intersect(g$down,rownames(z)); one[[paste0(program,"_score")]] <- colMeans(z[up,,drop=FALSE],na.rm=TRUE)-colMeans(z[down,,drop=FALSE],na.rm=TRUE); sum_rows <- append(sum_rows,list(data.frame(tag=s$tag,gsm=s$gsm,context=s$context,program=program,n_spots=ncol(z),median_score=median(one[[paste0(program,"_score")]],na.rm=TRUE),mean_score=mean(one[[paste0(program,"_score")]],na.rm=TRUE),q25=quantile(one[[paste0(program,"_score")]],0.25,na.rm=TRUE),q75=quantile(one[[paste0(program,"_score")]],0.75,na.rm=TRUE),stringsAsFactors=FALSE))); plot_dt <- one[is.finite(get(paste0(program,"_score")))]; plot_dt[,score_value:=get(paste0(program,"_score"))]; p1 <- ggplot(plot_dt,aes(x=pxl_col_in_fullres,y=pxl_row_in_fullres,color=score_value))+geom_point(size=.55)+scale_y_reverse()+coord_fixed()+scale_color_viridis_c(option="magma")+theme_void()+labs(title=paste0(s$tag," ",s$context," ",program),color="global z score"); fn <- file.path(plot_out,paste0(s$tag,"_",program,"_global_score.png")); ragg::agg_png(fn,width=1200,height=1000,res=180); print(p1); dev.off()}
  fwrite(one,file.path(out,"spot_tables",paste0(s$tag,"_spot_program_scores_global.tsv")),sep="\t",na="NA"); spot_rows <- append(spot_rows,list(one))
}
fwrite(rbindlist(sum_rows),file.path(out,"GSE327056_spatial_program_summary_global.tsv"),sep="\t",na="NA"); fwrite(rbindlist(spot_rows,fill=TRUE),file.path(out,"GSE327056_all_spot_program_scores_global.tsv"),sep="\t",na="NA"); fwrite(data.table(gene=all_genes,global_mean=mu,global_sd=sig),file.path(out,"GSE327056_program_gene_global_scaling.tsv"),sep="\t",na="NA"); writeLines(capture.output(sessionInfo()),file.path(out,"spatial_program_global_sessionInfo.txt"))
